const projectData = [
	{
		href: "fb-clone",
		title: "Facebook Clone",
		text: "A simple social app, you can post, like, unlike and comment.",
		image: 2,
		live: "https://facebook-clone-38694.web.app/",
		code: "https://github.com/truongwerk/fb-clone",
		features: [
			"Authentication with google.",
			"Add Post.",
			"Like and Unlike post.",
			"Add comment to post.",
			"Have realtime database with firebase.",
			"Global state (user) with Justand.",
			"Responsive.",
		],
		build: [
			"React.",
			"Firebase.",
			"Mui.",
			"Css.",
			"Zustand.",
			"Facebook page plugin.",
			"Webpack.",
		],
	},
	{
		href: "Memory-games",
		title: "Memory Games",
		text: "Train your memory muscles with Match Magic and Fruit Memorize!",
		image: 2,
		live: "https://truongwerk.github.io/Memory-games/",
		code: "https://github.com/truongwerk/Memory-games",
		features: ["Routing.", "Flip animation.", "2 games.", "Responsive."],
		build: ["React.", "React Router.", "Css.", "Vite."],
	},
	{
		href: "CV-Application",
		title: "CV Application",
		text: "Create a CV with: basic infos, contacts, skills...",
		image: 1,
		live: "https://truongwerk.github.io/CV-Application/",
		code: "https://github.com/truongwerk/CV-Application",
		features: [
			"Create a CV with: basic info, contacts, skill, education, experience.",
			"Skill,education, experience can add, change, delete.",
			"Changes apply instantly.",
			"Can save your CV to a PDF file.",
		],
		build: [
			"ReactJS.",
			"MUI and css.",
			"Use react-to-print library for printing.",
			"Bundle with webpack.",
			"Linting with ESlint and prettier.",
		],
	},
	{
		href: "Fortnite-Item-Store",
		title: "Fortnite Item Store",
		text: "A shopping cart with fortnite database.",
		image: 4,
		live: "https://truongwerk.github.io/Fortnite-Item-Store/#/store",
		code: "https://github.com/truongwerk/Fortnite-Item-Store",
		features: [
			"Routing.",
			"Dynamic Item page with unique url.",
			"Lazy loading.",
			"Add multiple items to cart.",
			"Show cart and total cost.",
			"Responsive.",
		],
		build: ["React.", "React router.", "MUI.", "Css.", "Vite."],
	},
	{
		href: "Weather-App",
		title: "Weather App",
		text: "Check current weather with search location or gps.",
		image: 1,
		live: "https://truongwerk.github.io/Weather-App/",
		code: "https://github.com/truongwerk/Weather-App",
		features: [
			"Search location with geocoding api.",
			"Get location with gps with reverse geocoding api.",
			"Check current weather with weather api.",
			"Celsius to fahrenheit and vice versa toggle.",
			"Responsive.",
		],
		build: [
			"Use https://openweathermap.org/ api.",
			"Vanilla javascript and css.",
			"Bundle with Webpack and Babel.",
			"Linting with ESlint and prettier.",
		],
	},
	{
		href: "Todo-List",
		title: "Todo List",
		text: "A simple Todo List can divide by project, date count. ",
		image: 1,
		live: "https://truongwerk.github.io/Todo-List/",
		code: "https://github.com/truongwerk/Todo-List",
		features: [
			"Add, delete, edit task.",
			"Add, delete project.",
			"Task has: Name, Target Date, Description, Project.",
			"Show tasks in Different modes: All, Today, This Week, Project.",
			"Data saved in local machine.",
			"Responsive.",
		],
		build: ["Vanilla JavaScript", "Vanilla Css.", "JS Modules.", "Webpack."],
	},
];

export default projectData;
